# Generated by Django 5.2.1 on 2025-05-25 11:32

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corkscrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(choices=[('wood', 'Wood'), ('stainless steel', 'Stainless'), ('steel', 'Steel')], default='stainless steel', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('romantic', 'Romantic'), ('festive', 'Festive'), ('casual', 'Casual')], default='festive', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_region', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.IntegerField(null=True)),
                ('price_range', models.CharField(choices=[('budget', 'Budget'), ('mid-range', 'Mid Range'), ('premium', 'Premium')], default='budget', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('wine', 'Wine'), ('glass', 'Glass'), ('corkscrew', 'Corkscrew')], default='wine', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_type', models.CharField(choices=[('dry', 'Dry'), ('semi_dry', 'Semi Dry'), ('semi_sweet', 'Semi Sweet'), ('dessert', 'Dessert'), ('sparkling', 'Sparkling')], default='dessert', max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rose')], default='red', max_length=20)),
                ('vintage_year', models.IntegerField(null=True)),
                ('alcohol', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Wine',
                'verbose_name_plural': 'Wines',
            },
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(null=True)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.CharField(choices=[('glass', 'Glass'), ('crystal', 'Crystal'), ('plastic', 'Plastic')], default='glass', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country')),
            ],
        ),
    ]
